import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Efrain's PricingPage",
    description: "Generated by create next app",
};

export default function PricingPage() {
    return (
        <>
            <span className="text-5xl">Pricing page</span>
        </>
    )
}