import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Efrain's ContactPage",
    description: "Generated by create next app",
};

export default function ContactPage() {
    return (
        <>
            <span className="text-5xl">Contact page</span>
        </>
    )
}