import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Efrain's AboutPage",
    description: "Generated by create next app",
};

export default function AboutPage() {
    return (
        <>
            <span className="text-5xl">About page</span>
        </>
    )
}