import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Efrain's HomePage",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="flex items-center p-24">
      <span className="text-5xl">Hola Mundo!</span>
    </main>
  );
}
